import pickle

if __name__ == '__main__':

    layouts = {
        'layout_input': ('X', 'BJI'),
        'layout_output': ('SB2', 'BJI'),
        'special_dims': {
            'AIB_DV': 'B',
            'AIB_DT': 'J',
            'SM_DV': 'J',
            'BDRLN1_DV': 'I',
            'BAD_DV': 'U',
            'BAD_DT': 'J',
            'BDRLN2_DV': 'J',
            'BSB_DV': 'I',
            'BSB_DW': 'B',
            'BLNRD1_DV': 'J',
            'BDRLB_DV': 'U',
            'BDRLB_DW': 'J',
            'EBSB_DV': 'J',
            'EBSB_DW': 'J',
            'BLNRD2_DV': 'J',
            'BAOB_DV': 'J',
            'BAOB_DW': 'B',
            'BS_DV': 'J',
            'BAIB_DV': 'J',
            'BAIB_DW': 'B',
            'BEI_DV': 'I',
            'BEI_DT': 'I',
        },
        'algorithms': {
            'WKKWQQWVV': 'DEFAULT',
            'BETA': 'ALGO3',
            'GAMMA': 'ALGO10',
            'ATT': 'ALGO3',
            'SB1_LINW1': 'ALGO3',
            'DROP2_LINW2': 'ALGO4',
            'DDROP2': 'DEFAULT',
            'DLINW2': 'DEFAULT',
            'DLIN1_LINW1': 'DEFAULT',
            'DLINW1': 'DEFAULT',
            'DWO': 'DEFAULT',
            'DGAMMA': 'DEFAULT',
            'DATTN_DROP': 'ALGO11',
            'DVV': 'ALGO10',
            'DQQ': 'ALGO2',
            'DKK': 'ALGO10',
            'DXATT': 'ALGO6',
            'DWKQV': 'DEFAULT',
        },
        'layouts_params': [
            ('WKQV', 'QHPI'),
            ('BKQV', 'QPH'),
            ('WO', 'PHI'),
            ('BO', 'I'),
            ('S1', 'I'),
            ('B1', 'I'),
            ('LINB1', 'U'),
            ('LINW1', 'IU'),
            ('S2', 'I'),
            ('B2', 'I'),
            ('LINB2', 'I'),
            ('LINW2', 'IU'),
        ],
        'layout_forward_interm': [
            ('KKQQVV', 'QPHBJ'),
            ('WKKWQQWVV', 'QHPBJ'),
            ('BETA', 'KHBJ'),
            ('ALPHA', 'KHBJ'),
            ('ATTN_DROP_MASK', 'HBJK'),
            ('ATTN_DROP', 'HBJK'),
            ('GAMMA', 'PHBJ'),
            ('ATT', 'BJI'),
            ('DROP1MASK', 'BJI'),
            ('SB1', 'IBJ'),
            ('SB1_LINW1', 'BJU'),
            ('DROP2', 'UBJ'),
            ('LIN1', 'UBJ'),
            ('DROP2_LINW2', 'BJI'),
            ('LIN2', 'BJI'),
            ('LN2', 'BJI'),
            ('LN2STD', 'BJ'),
            ('LN2DIFF', 'BJI'),
            ('DROP2MASK', 'UBJ'),
            ('DROP3MASK', 'BJI'),
            ('LN1', 'BJI'),
            ('LN1STD', 'JB'),
            ('LN1DIFF', 'BJI'),
        ],
        'layout_backward_interm': [
            ('DLN2', 'BJI'),
            ('DRESID2', 'IBJ'),
            ('DLIN2', 'BJI'),
            ('DDROP2', 'UBJ'),
            ('DLIN1', 'BJU'),
            ('DLIN1_LINW1', 'IBJ'),
            ('DLN1', 'IBJ'),
            ('DRESID1', 'IBJ'),
            ('DATT', 'IBJ'),
            ('DXATT', 'BJI'),
            ('DGAMMA', 'PHBJ'),
            ('DATTN_DROP', 'HBJK'),
            ('DBETA', 'KHBJ'),
            ('DKKQQVV', 'QHPBJ'),
        ]
    }

    with open('layouts.pickle', 'wb') as handle:
        pickle.dump(layouts, handle)
